name: 0. Terraform Backend Provisioning

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  deploy:
    name: 'Deploy Terraform state bucket'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Generate Terraform backend storage account suffix - 8 characters 
        id: random
        run: |
          random_suffix=$(cat /dev/urandom | tr -dc 'A-Z' | fold -w 8 | head -n 1)
          echo "Generated string: $random_suffix"
          echo "RANDOM_SUFFIX=$random_suffix" >> $GITHUB_ENV
          # create a new storage account name using the random suffix in an environment variable
          echo "TERRAFORM_STORAGE_ACCOUNT_NAME=terraform$random_suffix" >> $GITHUB_ENV
          echo "TERRAFORM_STORAGE_CONTAINER_NAME=tfstate" >> $GITHUB_ENV
 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create the Storage Account
        run: |
          az storage account create \
              --name  ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }} \
              --resource-group ${{ vars.AZURE_GROUP_NAME }} \
              --location ${{AZURE_LOCATION}} \
              --sku Standard_LRS \
              --allow-blob-public-access false

      - name: Create the Storage Container
        run: |
          az storage container create \
              --name tfstate \
              --account-name ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}

      - name: Save the name in the github axtion secret
        run: |
          gh secret set TERRAFORM_STORAGE_ACCOUNT_NAME -b ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }} 

      
