name: 0. Terraform Backend Provisioning

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  deploy:
    name: 'Deploy Terraform state bucket'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create the Storage Account
        run: |
          az storage account create \
              --name  terraformF1AB3C1F\
              --resource-group rg-webappphpmysql \
              --location westeurope \
              --sku Standard_LRS \
              --allow-blob-public-access false

      - name: Create the Storage Container
        run: |
          az storage container create \
              --name tfstate \
              --account-name terraformF1AB3C1F
