name: 0. Terraform Backend Provisioning

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy Terraform state bucket'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check if TERRAFORM_STORAGE_ACCOUNT_NAME is defined
        id: check-secret
        run: |
          if [ -z "${{ secrets.TERRAFORM_STORAGE_ACCOUNT_NAME }}" ]; then
            echo "Secret TERRAFORM_STORAGE_ACCOUNT_NAME is not defined, generating a random suffix."
            random_suffix=${RANDOM}${RANDOM}
            echo "Generated string: $random_suffix"
            echo "RANDOM_SUFFIX=$random_suffix" >> $GITHUB_ENV
            storage_account_name="terraform$random_suffix"
            echo "TERRAFORM_STORAGE_ACCOUNT_NAME=$storage_account_name" >> $GITHUB_ENV
          else
            echo "Using existing secret for TERRAFORM_STORAGE_ACCOUNT_NAME."
            echo "TERRAFORM_STORAGE_ACCOUNT_NAME=${{ secrets.TERRAFORM_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          fi
          echo "Storage Account Name: ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}"
        shell: bash

      - name: Set Container Name
        run: echo "TERRAFORM_STORAGE_CONTAINER_NAME=tfstate" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create the Storage Account
        run: |
          az storage account create \
              --name  ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }} \
              --resource-group ${{ vars.AZURE_GROUP_NAME }} \
              --location ${{ vars.AZURE_LOCATION }} \
              --sku Standard_LRS \
              --allow-blob-public-access false
          # if error stop the workflow and fail wih the error message
          if [ $? -ne 0 ]; then
            echo "Failed to create the storage account"
            exit 1
          fi

      - name: Create the Storage Container
        run: |
          az storage container create \
              --name ${{ env.TERRAFORM_STORAGE_CONTAINER_NAME }} \
              --account-name ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}

      - name: Save the name in the GitHub Action secret
        run: |
          gh secret set TERRAFORM_STORAGE_ACCOUNT_NAME -b ${{ env.TERRAFORM_STORAGE_ACCOUNT_NAME }}

