name: 3. Deploy the PHP Web App

on:
  push:
    branches: [ "main" ]
    # only changes are done to the webapp folder and the workflow file
    paths:
      - 'webapp/**'
      - '.github/workflows/3.deploy.webapp.yml'

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME:  "webapp-${{ vars.PROJECT_NAME }}" # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH:  './webapp' # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '8.1'  # set this to the PHP version to use

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up PHP ${{ env.PHP_VERSION }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: pdo_mysql

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        mv composer.phar /usr/local/bin/composer

    - name: Install dependencies
      run: composer install --working-dir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Build the web app
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        composer install
        composer dump-autoload --optimize

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # Deploy the web app to Azure Web Appq 
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact for deployment job
        uses: actions/download-artifact@v4
        with:
          name: webapp
  
      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           package: ${{ github.workspace }}




  # Deploy the web app to Azure Web App

  # build-and-deploy:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - name: Checkout the repository
  #     uses: actions/checkout@v4
    
  #   - name: Set up Azure CLI
  #     uses: azure/login@v2
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}
    
  #   - name: Deploy to Azure WebApp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #       slot-name: production
  #       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
