name: 2. Deploy Camera App

on:
#   push:
#     branches: [ "main" ]
#     # only from the react-webcam-app directory
#     paths:
#       - 'react-webcam-app/**'
#       - '.github/workflows/2.deploy-camera-app.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "webapp-${{ vars.PROJECT_NAME }}"        # set this to your application's name
  AZURE_WEBAPP_RESOURCE_GROUP: "rg-${{ vars.PROJECT_NAME }}"  # set this to your resource group
  AZURE_WEBAPP_PUBLISH_PROFILE:         # to be set by the deployment job
  AZURE_WEBAPP_PACKAGE_PATH: './webapp' # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '8.1'                    # set this to the PHP version to use


  permissions:
    contents: read
  
  jobs:
    infrastructure:
      name: 'Querry Infrastructure'
      runs-on: ubuntu-latest
  #
  # querry infrastructure to get the publish profile for the webapp
  #
  infrastructure:
    name: 'Querry Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: List Resource Groups
        run: az group list --output table
      - name: Check if the Resource Group exists
        id: check_rg
        # the name of the group is in the acrtion's environment variables
        run: az group exists --name ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }}  # check if the resource group exists
        # if it does not exist, error with red color and stop the workflow
        continue-on-error: false
      - name: Check if the application exists
        id: check_app
        run: | 
          az webapp show \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }}
        continue-on-error: false
      - name: Get the publish profile
        id: get_publish_profile
        run: |
          az webapp deployment list-publishing-profiles \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }} \
              --xml > $GITHUB_WORKSPACE/publishingProfile.xml
        continue-on-error: false
      - name: Display the publish profile
        if: steps.get_publish_profile.outputs.exitcode == 0
        run: cat $GITHUB_WORKSPACE/publishingProfile.xml
      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: publishingProfile
          path: ./publishingProfile.xml
        continue-on-error: false      
