name: 3. Deploy the PHP Web App

on:
  push:
    branches: [ "main" ]
    # only changes are done to the webapp folder and the workflow file
    paths:
      - 'webapp/**'
      - '.github/workflows/3.deploy.webapp.yml'

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "webapp-${{ vars.PROJECT_NAME }}"        # set this to your application's name
  AZURE_WEBAPP_RESOURCE_GROUP: "rg-${{ vars.PROJECT_NAME }}"  # set this to your resource group
  AZURE_WEBAPP_PUBLISH_PROFILE:         # to be set by the deployment job
  AZURE_WEBAPP_PACKAGE_PATH: './webapp' # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '8.1'                    # set this to the PHP version to use

permissions:
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: production
        package: ./webapp
